### ISSUE TITLE
TypeError when publishing the diagnostics message

### ISSUE THREAD

**Issue by Vicidel** [tue-robotics/node_alive#16]
I have an error when node_alive_server publishes the messages on diagnostics array. Below the complete crash log:

```
[INFO] [1614169474.023794]: Added '/command' to node_alive_server
[INFO] [1614169474.025917]: Added '/telemetry' to node_alive_server
[INFO] [1614169474.027950]: Added '/mavros' to node_alive_server
[INFO] [1614169474.030687]: Added '/safety' to node_alive_server
[INFO] [1614169474.041093]: Added '/rosout' to node_alive_server
[INFO] [1614169474.044432]: Added '/node_alive_server' to node_alive_server
ERROR: connection refused to [http://172.17.0.1:34649/]
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/diagnostic_msgs/msg/_DiagnosticArray.py", line 139, in serialize
    length = len(_x)
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1066, in publish
    serialize_message(b, self.seq, message)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/opt/ros/noetic/lib/python3/dist-packages/diagnostic_msgs/msg/_DiagnosticArray.py", line 145, in serialize
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 383, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 304, in check_type
    check_type(field_name + '[]', base_type, v)
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 314, in check_type
    check_type('%s.%s' % (field_name, n), t, getattr(field_val, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 304, in check_type
    check_type(field_name + '[]', base_type, v)
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 314, in check_type
    check_type('%s.%s' % (field_name, n), t, getattr(field_val, n))
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 275, in check_type
    raise SerializationError('field %s must be of type bytes or an ascii string' % field_name)
genpy.message.SerializationError: field status[].values[].value must be of type bytes or an ascii string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/workspace/src/node_alive/scripts/node_alive_server", line 139, in <module>
    server.loop()
  File "/home/workspace/src/node_alive/scripts/node_alive_server", line 130, in loop
    self.pub.publish(diagnostic_array)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field status[].values[].value must be of type bytes or an ascii string
```

The package detects the other nodes currently running correctly and their current states. Butwhen publishing it crashes with TypeError. Below I printed the diagnostic array just before publishing (this is only a extract for one node):

```
header: 
  seq: 1
  stamp: 
    secs: 1614169766
    nsecs: 546660184
  frame_id: ''
status: 
  - 
    level: 2
    name: "node_alive/safety"
    message: "is dead"
    hardware_id: ''
    values: 
      - 
        key: "NodeState"
        value: 3
```

Commenting the line containing the status_msg.values solved the issue: 
```
status_msg.values.append(KeyValue("NodeState", NodeState.Alive.value))
```

**Comment by MatthijsBurgh** [comment]
Sorry, I introduced this bug in the last update. It is now fixed in `noetic-devel`. This branch will be merged soon.

**Comment by Vicidel** [comment]
No worries, thank you for the quick answer. I will wait for the merge, for now I have the line commented (don't need it for my application)
